export const RELATIONSHIP_TYPES = [
  'contains', 'contained_by',
  'capital_is', 'capital_of',
  'worships', 'worshipped_by',
  'at_war_with',
  'allied_with',
  'created', 'created_by',
  'inhabits', 'inhabited_by',
  'located_in',
  'rules', 'ruled_by',
  'member_of', 'has_member',
  'invented', 'invented_by',
  'wields', 'wielded_by',
  'seeks', 'sought_by',
  'caused', 'caused_by',
  'participated_in', 'had_participant',
  'founded', 'founded_by',
  'destroyed', 'destroyed_by',
  'guarded_by', 'guards',
  'opposes', 'opposed_by',
  'originates_from', 'source_of',
  'borders',
  'trades_with',
  'influences',
  'protects',
  'summons',
] as const;

export type RelationshipType = typeof RELATIONSHIP_TYPES[number];

export function isBidirectionalPair(type: string): string | null {
  const map: Record<string, string> = {
    'contains': 'contained_by',
    'contained_by': 'contains',
    'capital_is': 'capital_of',
    'capital_of': 'capital_is',
    'worships': 'worshipped_by',
    'worshipped_by': 'worships',
    'at_war_with': 'at_war_with',
    'allied_with': 'allied_with',
    'created': 'created_by',
    'created_by': 'created',
    'inhabits': 'inhabited_by',
    'inhabited_by': 'inhabits',
    'rules': 'ruled_by',
    'ruled_by': 'rules',
    'member_of': 'has_member',
    'has_member': 'member_of',
    'invented': 'invented_by',
    'invented_by': 'invented',
    'wields': 'wielded_by',
    'wielded_by': 'wields',
    'seeks': 'sought_by',
    'sought_by': 'seeks',
    'caused': 'caused_by',
    'caused_by': 'caused',
    'participated_in': 'had_participant',
    'had_participant': 'participated_in',
    'founded': 'founded_by',
    'founded_by': 'founded',
    'destroyed': 'destroyed_by',
    'destroyed_by': 'destroyed',
    'guarded_by': 'guards',
    'guards': 'guarded_by',
    'opposes': 'opposed_by',
    'opposed_by': 'opposes',
    'originates_from': 'source_of',
    'source_of': 'originates_from',
    'borders': 'borders',
    'trades_with': 'trades_with',
    'influences': 'influences',
    'protects': 'protects',
    'summons': 'summons',
  };
  return map[type] ?? null;
}
